# Generated by Django 4.2.2 on 2023-06-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
