# Generated by Django 4.2.2 on 2023-06-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_approved_announcement_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='published_at',
            new_name='publish_at',
        ),
    ]
